allowBuilds:
  pandora-common: true
  sharp: true
  unrs-resolver: true
dangerouslyAllowAllBuilds: true

allowUnusedPatches: false
forceLegacyDeploy: true
injectWorkspacePackages: false
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - pandora-common
  # Renovate security update: sharp@0.35.0
  - sharp@0.35.0
nodeOptions: --no-warnings=ExperimentalWarning --experimental-vm-modules
strictPeerDependencies: true
updateNotifier: false
verifyDepsBeforeRun: error
