allowBuilds:
  pandora-common: true
  pandora-common@git+https://github.com/Project-Pandora-Game/pandora.git: true
  sharp: true
  unrs-resolver: true

allowUnusedPatches: false
forceLegacyDeploy: true
injectWorkspacePackages: false
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - pandora-common
nodeOptions: --no-warnings=ExperimentalWarning --experimental-vm-modules
strictPeerDependencies: true
updateNotifier: false
verifyDepsBeforeRun: install
