DefineAsset({
	name: 'Suitcase',
	size: 'large',
	graphics: 'graphics.json',
	colorization: {
		suitcase: {
			name: 'Suitcase',
			default: '#D5D5D5',
		},
		suitcase_latches: {
			name: 'Suitcase Latches',
			default: '#9f9f9fff',
		},
		restraints_support: {
			name: 'Restraints Support',
			default: '#E6E6E6',
		},
		restraints_belts: {
			name: 'Belts',
			default: '#363636ff',
		},
		restraints_belts_buckles: {
			name: 'Belts Buckles',
			default: '#9f9f9fff',
		}
	},
	// size:350, y:455, centered
	preview: null,//'preview.png',
	attributes: {
		provides: [
			'Play_furniture',
		],
	},
	poseLimits: {

	},
	modules: {
		status: {
			type: 'typed',
			name: 'Suitcase Status',
			variants: [
				{
					id: 'closed',
					name: 'Closed',
					default: true,
					properties: {
						stateFlags: {
							provides: ["closed_suitcase"],
						},
					},
				},
				{
					id: 'opened',
					name: 'Opened',
					properties: {
						poseLimits: {
							view: 'front',
							bones: {
								leg_r: -60,
								leg_l: -60,
								arm_r: [[75, 140]],
								elbow_r: [[-180, -125], [-15, 180]],
								arm_l: [[75, 140]],
								elbow_l: [[-180, -125], [-15, 180]],
							},
						},
					},
				},
			],
		},
		position: {
			type: 'typed',
			name: 'Closed Suitcase Position',
			variants: [
				{
					id: 'front',
					name: 'Front',
					default: true,
				},
				{
					id: 'side',
					name: 'Side',
				},
			],
		},
	},
	stateFlagCombinations: [
		{
			requiredFlags: ['closed_suitcase'],
			properties: {
				effects: {
					blockHands: true,
				},
				attributes: {
					hides: [
						'Body_base',
						'Head_base',
						'Ears',
						'Hair',
						'Hair_front',
						'Hair_back',
						'Hair_extension',
						'Eyebrows',
						'Eyes',
						'Eyes_right_open',
						'Eyes_left_open',
						'Eyes_right_closed',
						'Eyes_left_closed',
						'Nose',
						'Mouth',
						'Mouth_open_wide',
						'Mouth_open_teeth',
						'Mouth_tongue_out',
						'Body_texture',
						'Blush',
						'Bodymark',
						'Body_tattoo',
						'Sex',
						'Vulva',
						'Vulva_spread',
						'Penis',
						'Penis_flaccid',
						'Penis_erect',
						'Clothing',
						'Clothing_upper',
						'Clothing_lower',
						'Clothing_large',
						'Clothing_outer',
						'Underwear',
						'Underwear_bra',
						'Underwear_panties',
						'Underwear_corset',
						'Underwear_pants',
						'Underwear_diaper',
						'Fantasy',
						'Fantasy_ears',
						'Fantasy_tail',
						'Facewear',
						'Facewear_glasses',
						'Accessory',
						'Legwear',
						'Footwear',
						'Headgear',
						'Headgear_hood',
						'Wig',
						'Wig_front',
						'Wig_back',
						'Gloves',
						'Mittens',
						'Restraint',
						'Restraint_arms',
						'Wrist_cuffs',
						'Elbow_cuffs',
						'Restraint_torso',
						'Restraint_legs',
						'Ankle_cuffs',
						'Thigh_cuffs',
						'Restraint_eyes',
						'Toy',
						'Toy_clamps_genital',
						'Ear_item',
						'Restraint_ears',
						'Ear_insert',
						'Ear_cover',
						'Mouth_item',
						'Mouth_insert_deep',
						'Mouth_protruding',
						'Mouth_cover',
						'Hand_item',
						'Hand_cover',
						'Hand_restricting_cover',
						'Breast_item',
						'Breast_nipple',
						'Breast_cover',
						'Vulva_item',
						'Vulva_insert',
						'Vulva_insert_deep',
						'Vulva_cover',
						'Crotch_protruding',
						'Anus_item',
						'Anus_insert',
						'Anus_insert_deep',
						'Anus_protruding',
						'Anus_cover',
						'Collar',
						'Collar_front_ring',
						'Leash',
						'Chastity',
						'Handheld',
						'Piercing',

					],
				},
			},
		},
	],
	chat: {
		actionAdd: 'SOURCE_CHARACTER put TARGET_CHARACTER_DYNAMIC_POSSESSIVE inside a ITEM_ASSET_NAME',
		actionRemove: 'SOURCE_CHARACTER take off TARGET_CHARACTER_DYNAMIC_POSSESSIVE from ITEM_ASSET_NAME',
	},
	ownership: {
		responsibleContributor: 'Shikifet <shikifet@gmail.com>',
		credits: ['Shikifet'],
		modificationPolicy: `Fixes and New uses, otherwise ask`,
		reusePolicy: 'Ask first',
		licensing: [
			{
				source: 'Self-Made',
				copyrightHolder: 'Shikifet',
				editedBy: 'Shikifet',
				license: 'Pandora-Use-Only-v1-or-later',
			},
		],
	},
});
