#!/bin/bash

set -eou pipefail
source "./.hooks/include.sh"

submodule_update

PREV_COMMIT=$1
POST_COMMIT=$2

if [ -f pnpm-lock.yaml ]; then
	if [ "$(git --no-pager diff --shortstat $PREV_COMMIT..$POST_COMMIT pnpm-lock.yaml pandora)" != "" ]; then
		pnpm_helper
	fi
fi
